### ISSUE TITLE
Login API request example doesn't work - includes newline in login JSON body

### ISSUE THREAD

**Issue by obs-gh-wade** [observeinc/observe-export#13]
You get the following error without removing the newline:

```
{"ok":false,"message":"Malformed login request"}
```

**Comment by MatthiasObserve** [comment]
Hey Wade, can you specify what's exactly supposed to be changed? Am not too sure here. Thanks

**Comment by obs-gh-felixbowing** [comment]
I guess you are referring to the fact that the token generation fails if the json contains a line break in the following curl command: 

`curl -s \
  https://${OBSERVE_CUSTOMER}.observeinc.com/v1/login -d \
  '{"user_email":"you@your-company.com", "user_password":"so secret", \
  "tokenName":"My token name"}'`

We will remove that to prevent confusion. Thanks for pointing that out!
